use_frameworks!

platform :ios, '10.0'

target 'CustomPodsDemoExample_Example' do
  pod 'CustomPodsDemoExample', :path => '../'

  target 'CustomPodsDemoExample_Tests' do
    inherit! :search_paths

    
  end
end
