use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

target 'CustomPodsDemoExample_Example' do
  pod 'CustomPodsDemoExample', :path => '../'

  target 'CustomPodsDemoExample_Tests' do
    inherit! :search_paths

    
  end
end
